### ISSUE TITLE
[Attestation] 

### ISSUE THREAD

**Issue by minogue07** [nimiq/ceremony-attestations#73]
**What was your Nimiq ceremony address (public key)?**

5ca192e89d34919efb8a5e7103cf289ec9e168a8eeb7dd52e5327b8213485d38

**What's your name (optional)?**

Mickyblizz

**What's your affiliation (optional)?**

Round 7

**Did you attest on other platforms (Twitter/Keybase/etc) (optional)? If so, please add links to the attestations here!**

ADD LINKS HERE

**Please attach the attestation file!**

CLICK ATTACH AT THE BOTTOM AND ATTACH THE `nimiq.attestation` FILE

**Comment by ii-cruz** [comment]
@minogue07 you forgot to attach the attestation

**Comment by minogue07** [comment]
OMG I lost my attestation file, is there a way I could get it done I got the attestation info late do I need to redo the contribution?

**Comment by ii-cruz** [comment]
It's ok, don't worry, the attestation is optional either way. Your contribution is there and if you have destroyed all the keys all is good :) 

I'll close the issue.

**Comment by minogue07** [comment]
Thank you
